orth_admin:
    resource: "@OrthAdminBundle/Resources/config/routing.yml"
    prefix:   /

orth_index:
    resource: "@OrthIndexBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
