<?php

namespace Orth\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApprovalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovalRepository extends EntityRepository
{
}
